async def error_mock(*_):
    raise Exception("mock error")
